# ASP.NET Core tag
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  MajorVersion: 3
  MinorVersion: 0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]
  version: '$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)'
  solution: 'ServerBrowser.sln'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
    nugetConfigPath: 'nuget.config'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: true

- task: CmdLine@2
  inputs:
    script: 'rename s.zip ddayserverbrowser-windows-$(version).zip'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_schovan'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(version)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'