# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'ServerBrowser.sln'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
    nugetConfigPath: 'nuget.config'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: Artifact ServerBrowser.zip
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/s'
    artifactName: ServerBrowser

- task: GitHubRelease@1
  inputs:
    gitHubConnection: schovan
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
